# Site settings
title: "The Owlery"
email: "chasem000@gmail.com"
description: "Description"
url: "http://theowlery.co"

# Build settings
markdown: kramdown
highlighter: rouge

permalink: /:year/:month/:title

excerpt_separator: "\n\n"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: post
  -
    scope:
      path: "_posts/asides"
      type: "posts"
    values:
      category: "asides"
  -
    scope:
      path: "_posts/columns"
      type: "posts"
    values:
      category: "columns"
  -
    scope:
      path: "_posts/quotes"
      type: "posts"
    values:
      category: "quotes"
